SKILL_KEYWORDS = [

    # ---------- Programming Languages ----------
    "python", "java", "javascript", "typescript", "c", "c++", "c#", "go", "golang",
    "ruby", "php", "rust", "kotlin", "swift", "scala", "r", "matlab",
    "perl", "bash", "shell scripting",

    # ---------- Backend Development ----------
    "django", "flask", "fastapi", "spring", "spring boot", "hibernate",
    "node", "express", "nestjs", "laravel", "codeigniter", "rails",
    ".net", "asp.net", "asp.net core",

    # ---------- Frontend Development ----------
    "react", "angular", "vue", "next.js", "nuxt",
    "html", "css", "sass", "scss",
    "bootstrap", "tailwind", "material ui", "ant design", "jquery",
    "redux", "vuex", "webpack", "vite",

    # ---------- Mobile Development ----------
    "android", "android studio", "ios", "xcode",
    "flutter", "dart", "react native", "ionic",

    # ---------- Databases ----------
    "mysql", "postgresql", "sqlite", "sql server",
    "mongodb", "cassandra", "dynamodb", "redis", "firebase",
    "elasticsearch", "kafka",

    # ---------- Cloud & DevOps ----------
    "aws", "azure", "gcp", "heroku", "digitalocean",
    "docker", "kubernetes", "helm", "istio",
    "jenkins", "github actions", "gitlab ci",
    "terraform", "ansible",
    "linux", "unix", "nginx", "apache",
    "prometheus", "grafana",

    # # ---------- Data Science & AI/ML ----------
    # "machine learning", "deep learning", "data science", "data analysis",
    # "pandas", "numpy", "scikit-learn", "tensorflow", "pytorch",
    # "nlp", "computer vision", "power bi", "tableau",

    # ---------- Low-Code/No-Code Platforms ----------
    "power apps", "power automate", "mendix", "outsystems",
    # "salesforce", "salesforce admin", "salesforce developer",
    "zoho crm", "dynamics 365", "servicenow",
    "wix", "webflow",

    # ---------- E-commerce & CMS ----------
    "wordpress", "woocommerce", "shopify", "magento",
    "drupal", "joomla",

    # ---------- ERP & Business Systems ----------
    # "sap", "sap fico", "sap mm", "sap abap",

    # ---------- UI/UX Design ----------
    "ui", "ux", "ui/ux", "figma", "adobe xd",
    "photoshop", "illustrator", "sketch",

    # ---------- APIs & Integration ----------
    "rest", "rest api", "graphql", "soap",
    "microservices", "webhooks",

    # ---------- Testing & QA ----------
    "manual testing", "automation testing",
    "selenium", "cypress", "playwright",
    "junit", "pytest", "jest", "mocha", "chai", "postman",

    # ---------- Project Management ----------
    "agile", "scrum", "jira", "confluence",

    # ---------- Version Control ----------
    "git", "github", "gitlab", "bitbucket",

    # ---------- Cybersecurity ----------
    "cyber security", "ethical hacking", "networking",

    # ---------- Emerging Technologies ----------
    "blockchain", "web3",
    
    # ============================================
        # ---------- SAP Suite (Complete) ----------
    "sap", "sap abap", "sap abap objects", "sap abap oops", "sap abap hr", "sap abap webdynpro",
    "sap fico", "sap fi", "sap co", "sap general ledger", "sap accounts payable", "sap accounts receivable",
    "sap asset accounting", "sap cost center accounting", "sap profit center accounting", 
    "sap product costing", "sap fiori", "sap s4 hana", "sap s4hana finance", "sap central finance",
    "sap mm", "sap materials management", "sap procurement", "sap inventory management",
    "sap vendor evaluation", "sap purchasing", "sap sd", "sap sales and distribution",
    "sap sales order management", "sap billing", "sap shipping", "sap credit management",
    "sap pp", "sap production planning", "sap mrp", "sap capacity planning", "sap demand management",
    "sap qm", "sap quality management", "sap inspection planning", "sap quality certificates",
    "sap pm", "sap plant maintenance", "sap maintenance orders", "sap preventive maintenance",
    "sap ps", "sap project system", "sap wbs", "sap network planning",
    "sap hcm", "sap human capital management", "sap payroll", "sap time management",
    "sap successfactors", "sap hr", "sap organizational management", "sap personnel administration",
    "sap basis", "sap administration", "sap transport management", "sap performance tuning",
    "sap security", "sap authorization", "sap grc", "sap access control",
    "sap bw", "sap business warehouse", "sap bi", "sap business intelligence",
    "sap bw4 hana", "sap hana", "sap hana modeling", "sap hana sql", "sap hana xs",
    "sap bpc", "sap business planning and consolidation", "sap epm",
    "sap crm", "sap customer relationship management", "sap marketing", "sap sales",
    "sap scm", "sap supply chain management", "sap apo", "sap advanced planner optimizer",
    "sap ewm", "sap extended warehouse management", "sap tm", "sap transportation management",
    "sap gts", "sap global trade services", "sap ariba", "sap procurement cloud",
    "sap fieldglass", "sap contingent workforce", "sap concur", "sap travel management",
    "sap hybris", "sap commerce cloud", "sap cx", "sap customer experience",
    "sap leonardo", "sap iot", "sap machine learning", "sap analytics cloud",
    "sap cloud platform", "sap btp", "sap business technology platform",
    "sap fiori elements", "sap ux", "sap ui5", "sap sapui5", "sap openui5",
    "sap netweaver", "sap pi", "sap po", "sap process orchestration",
    "sap cloud integration", "sap cpi", "sap data services", "sap bods",
    "sap solution manager", "sap charm", "sap focus build", "sap activate",
    "sap ltmom", "sap test data migration server", "sap tdms",
    "sap solman", "sap cha rm", "sap focus run",
    
        # ---------- Salesforce (Complete) ----------
    "salesforce", "salesforce admin", "salesforce administrator", "salesforce developer",
    "salesforce architecture", "salesforce consultant", "salesforce ba", "salesforce business analyst",
    "salesforce cpq", "salesforce steelbrick", "salesforce quote to cash",
    "salesforce sales cloud", "salesforce service cloud", "salesforce marketing cloud",
    "salesforce pardot", "salesforce marketing cloud account engagement",
    "salesforce commerce cloud", "salesforce demandware", "salesforce b2b commerce",
    "salesforce b2c commerce", "salesforce community cloud", "salesforce experience cloud",
    "salesforce einstein", "salesforce ai", "salesforce analytics", "salesforce tableau",
    "salesforce crm", "salesforce lightning", "salesforce classic", "salesforce lightning experience",
    "salesforce lwc", "salesforce lightning web components", "salesforce aura components",
    "salesforce visualforce", "salesforce apex", "salesforce apex triggers", "salesforce apex classes",
    "salesforce soql", "salesforce sosl", "salesforce data loader", "salesforce dataloader io",
    "salesforce workbench", "salesforce dev console", "salesforce process builder",
    "salesforce flow", "salesforce screen flows", "salesforce autolaunched flows",
    "salesforce scheduled flows", "salesforce platform events", "salesforce custom metadata",
    "salesforce custom settings", "salesforce validation rules", "salesforce formula fields",
    "salesforce rollup summary fields", "salesforce reports", "salesforce dashboards",
    "salesforce workflows", "salesforce approval processes", "salesforce sandbox",
    "salesforce deployment", "salesforce change sets", "salesforce ant migration tool",
    "salesforce sfdx", "salesforce cli", "salesforce scratch orgs", "salesforce packaging",
    "salesforce managed packages", "salesforce unmanaged packages", "salesforce appexchange",
    "salesforce integration", "salesforce rest api", "salesforce soap api", "salesforce bulk api",
    "salesforce streaming api", "salesforce outbound messaging", "salesforce platform cache",
    "salesforce shield", "salesforce platform encryption", "salesforce event monitoring",
    "salesforce field audit trail", "salesforce health check", "salesforce security",
    "salesforce sharing rules", "salesforce profiles", "salesforce permission sets",
    "salesforce roles", "salesforce territory management", "salesforce forecasting",
    "salesforce campaigns", "salesforce leads", "salesforce opportunities", "salesforce accounts",
    "salesforce contacts", "salesforce cases", "salesforce solutions", "salesforce knowledge",
    "salesforce entitlements", "salesforce milestone", "salesforce omni channel",
    "salesforce digital engagement", "salesforce live agent", "salesforce chatbots",
    "salesforce einstein bots", "salesforce service cloud voice",
    "salesforce field service", "salesforce field service lightning",
    "salesforce cdp", "salesforce customer data platform",
    "salesforce datorama", "salesforce mulesoft", "salesforce integration cloud",
    "salesforce slack", "salesforce sales engagement", "salesforce high velocity sales",
    "salesforce revenue cloud", "salesforce billing", "salesforce crm analytics",
    "salesforce trailhead", "salesforce certifications", "salesforce platform app builder",
    "salesforce platform developer I", "salesforce platform developer II",
    "salesforce javascript developer", "salesforce data architect",
    "salesforce application architect", "salesforce system architect",
    "salesforce b2b solution architect", "salesforce b2c solution architect",
    "salesforce industry clouds", "salesforce financial services cloud",
    "salesforce health cloud", "salesforce manufacturing cloud",
    "salesforce consumer goods cloud", "salesforce sustainability cloud",
    "salesforce nonprofit cloud", "salesforce education cloud",
    "salesforce public sector solutions", "salesforce partner relationship management",
    "salesforce medallia", "salesforce vlocity", "salesforce omnistudio",
    "salesforce industry cpq", "salesforce industry apis", "salesforce digital experiences",
    
        # ---------- Oracle (Complete) ----------
    "oracle", "oracle database", "oracle db", "oracle sql", "oracle plsql", "oracle forms",
    "oracle reports", "oracle apex", "oracle application express", "oracle enterprise manager",
    "oracle grid", "oracle asm", "oracle rac", "oracle real application clusters",
    "oracle dataguard", "oracle golden gate", "oracle fusion middleware",
    "oracle weblogic", "oracle webcenter", "oracle soa suite", "oracle osb",
    "oracle bpm", "oracle business process management", "oracle identity management",
    "oracle access manager", "oracle internet directory", "oracle unified directory",
    "oracle ebs", "oracle e business suite", "oracle financials", "oracle scm",
    "oracle hcm", "oracle crm", "oracle manufacturing", "oracle projects",
    "oracle apps technical", "oracle apps functional", "oracle apps dba",
    "oracle fusion", "oracle fusion apps", "oracle fusion cloud", "oracle cloud erp",
    "oracle cloud hcm", "oracle cloud scm", "oracle cloud cxm", "oracle cloud crm",
    "oracle netsuite", "oracle erp cloud", "oracle financials cloud",
    "oracle procurement cloud", "oracle risk management cloud",
    "oracle enterprise performance management", "oracle epm cloud", "oracle planning",
    "oracle budgeting", "oracle consolidation", "oracle account reconciliation",
    "oracle tax reporting", "oracle narrative reporting", "oracle profitability",
    "oracle jd edwards", "oracle jde", "oracle enterprise one", "oracle world",
    "oracle peoplesoft", "oracle peoplesoft hcm", "oracle peoplesoft financials",
    "oracle peoplesoft campus solutions", "oracle peoplesoft elm",
    "oracle siebel", "oracle siebel crm", "oracle customer relationship management",
    "oracle hyperion", "oracle hyperion planning", "oracle hyperion financial management",
    "oracle essbase", "oracle smart view", "oracle financial consolidation",
    "oracle analytics", "oracle analytics cloud", "oracle bi", "oracle business intelligence",
    "oracle oac", "oracle obiee", "oracle bi publisher", "oracle dv", "oracle data visualization",
    "oracle machine learning", "oracle autonomous database", "oracle adw", "oracle autonomous data warehouse",
    "oracle atp", "oracle autonomous transaction processing", "oracle mysql",
    "oracle nosql", "oracle berkeley db", "oracle times ten", "oracle in memory",
    "oracle exadata", "oracle database appliance", "oracle zero data loss recovery appliance",
    "oracle cloud infrastructure", "oracle oci", "oracle compute", "oracle storage",
    "oracle networking", "oracle load balancer", "oracle vpn", "oracle fastconnect",
    "oracle container engine", "oracle oke", "oracle functions", "oracle api gateway",
    "oracle streaming", "oracle events", "oracle notifications",
    "oracle integration cloud", "oracle oic", "oracle process cloud", "oracle visual builder",
    "oracle vbc s", "oracle mobile cloud", "oracle chatbot", "oracle digital assistant",
    "oracle blockchain", "oracle blockchain platform", "oracle iot", "oracle iot cloud",
    "oracle security", "oracle cloud guard", "oracle vulnerability scanning",
    "oracle os management", "oracle key management", "oracle waas",
    "oracle data safe", "oracle identity cloud service", "oracle idcs",
    "oracle java", "oracle jdk", "oracle jre", "oracle graalvm", "oracle helidon",
    "oracle coherence", "oracle web logic server", "oracle glassfish",
    "oracle linux", "oracle solaris", "oracle vm", "oracle virtualbox",
    "oracle developer cloud", "oracle management cloud", "oracle application performance monitoring",
    "oracle apm", "oracle log analytics", "oracle it analytics",
    "oracle cx", "oracle customer experience", "oracle marketing cloud",
    "oracle sales cloud", "oracle service cloud", "oracle commerce cloud",
    "oracle loyalty cloud", "oracle configure price quote", "oracle cpq",
    "oracle policy automation", "oropa", "oracle knowledge management",
    "oracle field service", "oracle subscriptions", "oracle revenue management",
    "oracle transportatio n management", "oracle tms", "oracle global trade management",
    "oracle warehouse management", "oracle wms", "oracle supply chain planning",
    "oracle demand management", "oracle order management", "oracle inventory",
    "oracle manufacturing cloud", "oracle maintenance cloud", "oracle quality",
    "oracle product lifecycle management", "oracle agile", "oracle product hub",
    "oracle learning cloud", "oracle talent management", "oracle recruit",
    "oracle performance management", "oracle compensation", "oracle workforce management",
    "oracle time and labor", "oracle payroll", "oracle benefits", "oracle absence",
    "oracle hcm analytics", "oracle journey science", "oracle infinity",
    
    
        # ---------- AI/ML (Complete) ----------
    "ai", "artificial intelligence", "machine learning", "ml", "deep learning", "dl",
    "neural networks", "cnn", "convolutional neural networks", "rnn", "recurrent neural networks",
    "lstm", "long short term memory", "gru", "gated recurrent units",
    "transformer", "attention mechanism", "bert", "gpt", "openai", "chatgpt",
    "generative ai", "gans", "generative adversarial networks", "vae", "variational autoencoders",
    "reinforcement learning", "rl", "q learning", "deep q networks", "policy gradients",
    "computer vision", "cv", "image processing", "object detection", "yolo", "ssd", "faster rcnn",
    "image segmentation", "semantic segmentation", "instance segmentation", "mask rcnn",
    "facial recognition", "ocr", "optical character recognition", "object tracking",
    "nlp", "natural language processing", "text mining", "sentiment analysis",
    "named entity recognition", "ner", "text classification", "topic modeling",
    "word embeddings", "word2vec", "glove", "fasttext", "transformers", "huggingface",
    "speech recognition", "speech to text", "text to speech", "voice recognition",
    "recommender systems", "collaborative filtering", "content based filtering",
    "time series analysis", "forecasting", "arima", "sarima", "prophet",
    "anomaly detection", "fraud detection", "predictive analytics", "prescriptive analytics",
    "supervised learning", "unsupervised learning", "semi supervised learning",
    "self supervised learning", "transfer learning", "few shot learning", "zero shot learning",
    "feature engineering", "feature selection", "dimensionality reduction", "pca", "t sne",
    "clustering", "k means", "hierarchical clustering", "dbscan", "gaussian mixture models",
    "classification", "logistic regression", "decision trees", "random forest", "xgboost",
    "lightgbm", "catboost", "svm", "support vector machines", "naive bayes", "knn",
    "regression", "linear regression", "polynomial regression", "ridge regression",
    "lasso regression", "elastic net", "gradient boosting", "adaboost",
    "hyperparameter tuning", "grid search", "random search", "bayesian optimization",
    "model deployment", "mlops", "model serving", "tensorflow serving", "torchserve",
    "model monitoring", "model drift", "explainable ai", "xai", "model interpretability",
    "shap", "lime", "automl", "auto machine learning", "neural architecture search",
    "federated learning", "edge ai", "iot ai", "computer vision on edge",
    "robotics", "autonomous vehicles", "self driving cars", "drone ai",
    "healthcare ai", "medical imaging", "drug discovery", "bioinformatics",
    "finance ai", "algorithmic trading", "credit scoring", "risk assessment",
    "retail ai", "demand forecasting", "price optimization", "customer analytics",
    "manufacturing ai", "predictive maintenance", "quality control", "supply chain optimization",
    "agriculture ai", "precision farming", "crop monitoring", "yield prediction",
    "education ai", "adaptive learning", "intelligent tutoring systems",
    "legal ai", "document analysis", "contract review", "legal research",
    "creative ai", "art generation", "music generation", "text generation",
    "ethical ai", "ai ethics", "bias mitigation", "fairness in ai", "ai safety",
    "quantum machine learning", "neuromorphic computing", "spiking neural networks",
    "tensorflow", "pytorch", "keras", "scikit learn", "mxnet", "caffe", "caffe2",
    "jax", "theano", "cntk", "onnx", "openvino", "tensorrt", "core ml",
    "hugging face transformers", "spacy", "nltk", "gensim", "stanford nlp",
    "opencv", "pillow", "scikit image", "simpleitk", "medpy",
    "pandas", "numpy", "scipy", "matplotlib", "seaborn", "plotly", "bokeh",
    "dask", "ray", "apache spark ml", "h2o ai", "rapids", "cuml",
    "mlflow", "kubeflow", "metaflow", "prefect", "airflow ml",
    "sagemaker", "azure ml", "vertex ai", "databricks", "hugging face spaces",
    "streamlit", "gradio", "fastapi ml", "flask ml", "docker ml",
    "kubernetes ml", "seldon core", "bentoml", "cortex", "triton inference server",
    "prometheus ml", "grafana ml", "evidently ai", "great expectations",
    "weka", "orange", "knime", "rapidminer", "dataiku", "alteryx",
    "tableau prep", "power bi ai", "qlik sense", "looker ml",
    "cognitive services", "ibm watson", "google cloud ai", "aws ai services",
    "azure cognitive services", "computer vision api", "language understanding",
    "face api", "text analytics", "translator", "speech services",
    "anomaly detector", "personalizer", "form recognizer", "metrics advisor",
    "custom vision", "language studio", "speech studio", "openai api",
    "cohere", "anthropic", "stability ai", "midjourney", "dalle",
    "stable diffusion", "imagen", "parti", "make a scene",
    "chatbots", "virtual assistants", "alexa skills", "google assistant",
    "dialogflow", "rasa", "botpress", "microsoft bot framework",
    "voice ai", "speech synthesis", "voice cloning", "voice conversion",
    "multimodal ai", "vision language models", "clip", "dall e",
    "vqa", "visual question answering", "image captioning",
    "ai chips", "tpu", "gpu programming", "cuda", "opencl", "rocm",
    "ai hardware", "nvidia dgx", "google tpu", "intel habana",
    "edge tpu", "jetson", "raspberry pi ai", "arduino ai",
    "ai in cloud", "serverless ai", "function as a service ai",
    "ai governance", "model registry", "data lineage", "ml metadata",
    "synthetic data", "data augmentation", "gan for data generation",
    "active learning", "human in the loop", "label studio", "prodigy",
    "data labeling", "annotation tools", "scale ai", "appen", "lionbridge ai",
]