# Generated by Django 5.2.10 on 2026-03-10 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gstin', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='invoices/company/logo/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='invoices/company/signature/')),
                ('default_gst_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('default_sac_code', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('default_terms', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_finance_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
