# Generated by Django 5.2.10 on 2026-05-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='margin',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tds',
            field=models.DecimalField(decimal_places=2, default=0, help_text='TDS percentage (0-15%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tds_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendor_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost paid to vendor for this invoice', max_digits=12),
        ),
    ]
