# Generated by Django 5.2.10 on 2026-03-10 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0021_candidate_google_event_id_and_more'),
        ('invoicing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('CANDIDATE', 'Candidate Invoice'), ('CUSTOM', 'Custom Invoice')], max_length=20)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('bill_to_name', models.CharField(max_length=255)),
                ('bill_to_company', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_to_address', models.TextField(blank=True, null=True)),
                ('bill_to_gstin', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bill_to_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField()),
                ('sac_code', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice_date', models.DateField()),
                ('billing_month', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/generated/')),
                ('external_invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/external/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='employee_portal.candidate')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_portal.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_portal.vendor')),
            ],
        ),
    ]
