# Generated by Django 5.2.10 on 2026-05-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_invoice_margin_invoice_payment_status_invoice_tds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='margin',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tds',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='TDS percentage (0-15%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tds_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vendor_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Cost paid to vendor for this invoice', max_digits=12, null=True),
        ),
    ]
