# Generated by Django 5.2.10 on 2026-03-13 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0022_candidate_billing_end_date_and_more'),
        ('invoicing', '0004_invoicehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='actual_working_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='per_day_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='total_working_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='InvoiceCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_invoices', to='employee_portal.candidate')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_candidates', to='invoicing.invoice')),
            ],
        ),
    ]
