# Generated by Django 5.2.10 on 2026-03-13 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_invoiceitem_actual_working_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='actual_working_days',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='per_day_rate',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='total_working_days',
        ),
        migrations.DeleteModel(
            name='InvoiceCandidate',
        ),
    ]
