# Generated by Django 5.2.10 on 2026-03-16 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0023_client_account_holder_name_client_account_number_and_more'),
        ('invoicing', '0006_remove_invoiceitem_actual_working_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyfinancesettings',
            name='account_holder_name',
        ),
        migrations.RemoveField(
            model_name='companyfinancesettings',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='companyfinancesettings',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='companyfinancesettings',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='rate',
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_type',
            field=models.CharField(choices=[('BILLABLE_DAYS', 'Billable Days'), ('HOURLY', 'Hourly Billing'), ('MANUAL', 'Manual Item')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_sow',
            field=models.FileField(blank=True, null=True, upload_to='invoices/client_sow/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='timesheet_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/timesheets/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendor_sow',
            field=models.FileField(blank=True, null=True, upload_to='invoices/vendor_sow/'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='billing_type',
            field=models.CharField(choices=[('BILLABLE_DAYS', 'Billable Days'), ('HOURLY', 'Hourly Billing'), ('MANUAL', 'Manual Item')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_portal.candidate'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='client_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='total_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='vendor_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='working_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.companybankaccount'),
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI'), ('STRIPE', 'Stripe'), ('RAZORPAY', 'Razorpay'), ('CASH', 'Cash')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoicing.invoice')),
            ],
        ),
    ]
