# Generated by Django 5.2.10 on 2026-03-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_alter_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sac_code',
        ),
    ]
