# Generated by Django 5.2.10 on 2026-03-19 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_portal', '0024_candidate_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Requirement Title / JD Name')),
                ('experience_required', models.CharField(max_length=50, verbose_name='Experience Required (Years)')),
                ('rate', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rate (Optional)')),
                ('time_zone', models.CharField(max_length=100, verbose_name='Time Zone')),
                ('jd_description', models.TextField(verbose_name='JD Description')),
                ('skills', models.TextField(help_text='Comma separated skills (e.g., Python, Django, React)', verbose_name='Skills')),
                ('requirement_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Requirement ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='employee_portal.client', verbose_name='Client Name')),
                ('company', models.ForeignKey(help_text='Jis company ka Sub-Admin hai', limit_choices_to={'role': 'SUB_ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_requirements', to=settings.AUTH_USER_MODEL, verbose_name='Company (Sub-Admin)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requirements', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Requirement',
                'verbose_name_plural': 'Requirements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateJDSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jd_submissions', to='employee_portal.candidate')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='company_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_candidates_jd', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_submissions', to='jd_mapping.requirement')),
            ],
            options={
                'verbose_name': 'Candidate JD Submission',
                'verbose_name_plural': 'Candidate JD Submissions',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='RequirementAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by_requirements', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'role': 'EMPLOYEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_requirements', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='company_assignments', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='jd_mapping.requirement')),
            ],
            options={
                'verbose_name': 'Requirement Assignment',
                'verbose_name_plural': 'Requirement Assignments',
            },
        ),
        migrations.CreateModel(
            name='AssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='jd_mapping.requirementassignment')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementIDCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=4)),
                ('last_sequence', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(limit_choices_to={'role': 'SUB_ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_counters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requirement ID Counter',
                'verbose_name_plural': 'Requirement ID Counters',
            },
        ),
        migrations.CreateModel(
            name='RequirementSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='company_skills', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_list', to='jd_mapping.requirement')),
            ],
            options={
                'verbose_name': 'Requirement Skill',
                'verbose_name_plural': 'Requirement Skills',
            },
        ),
        migrations.CreateModel(
            name='SubmissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='jd_mapping.candidatejdsubmission')),
            ],
            options={
                'verbose_name': 'Submission History',
                'verbose_name_plural': 'Submission Histories',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['company', '-created_at'], name='jd_mapping__company_72cf7c_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['requirement_id'], name='jd_mapping__require_083925_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['is_deleted'], name='jd_mapping__is_dele_0b8a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatejdsubmission',
            index=models.Index(fields=['company', '-submission_date'], name='jd_mapping__company_7943c6_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatejdsubmission',
            index=models.Index(fields=['requirement', 'submitted_by'], name='jd_mapping__require_9d8614_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatejdsubmission',
            index=models.Index(fields=['candidate'], name='jd_mapping__candida_d388c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatejdsubmission',
            unique_together={('candidate', 'requirement')},
        ),
        migrations.AddIndex(
            model_name='requirementassignment',
            index=models.Index(fields=['company', 'assigned_to'], name='jd_mapping__company_3550b5_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementassignment',
            index=models.Index(fields=['requirement', 'assigned_to'], name='jd_mapping__require_49e5b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requirementassignment',
            unique_together={('requirement', 'assigned_to')},
        ),
        migrations.AlterUniqueTogether(
            name='requirementidcounter',
            unique_together={('month', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='requirementskill',
            unique_together={('requirement', 'skill_name')},
        ),
    ]
