# Generated by Django 5.2.10 on 2026-03-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jd_mapping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma separated skills (e.g., Python, Django, React)', null=True, verbose_name='Skills'),
        ),
    ]
