# Generated by Django 5.2.10 on 2026-02-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screeningstatushistory',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='screeningstatushistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='screening_status',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience_years',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(blank=True, choices=[('SELECTED', 'Selected'), ('REJECTED', 'Rejected'), ('DROP', 'Drop'), ('PIPELINE', 'Pipeline'), ('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('NOT_MATCHED', 'Not Matched'), ('HOLD', 'Hold')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='remarkhistory',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PipelineHistory',
        ),
        migrations.DeleteModel(
            name='ScreeningStatusHistory',
        ),
    ]
