# Generated by Django 5.2.10 on 2026-02-05 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0002_remove_screeningstatushistory_candidate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_pan_or_reg_no', models.CharField(blank=True, max_length=100, null=True)),
                ('poc1_name', models.CharField(blank=True, max_length=255, null=True)),
                ('poc1_number', models.CharField(blank=True, max_length=15, null=True)),
                ('poc2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('poc2_number', models.CharField(blank=True, max_length=15, null=True)),
                ('top_3_clients', models.TextField(blank=True, null=True)),
                ('no_of_bench_developers', models.PositiveIntegerField(blank=True, null=True)),
                ('provide_onsite', models.BooleanField(default=False)),
                ('onsite_location', models.CharField(blank=True, max_length=255, null=True)),
                ('specialized_tech_developers', models.TextField(blank=True, null=True)),
                ('bench_list', models.FileField(blank=True, null=True, upload_to='vendor/bench_list/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
