# Generated by Django 5.2.10 on 2026-02-06 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0004_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statushistory',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='statushistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='recruiter',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='status',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='vendor_name',
        ),
        migrations.AddField(
            model_name='candidate',
            name='blocklisted_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_email',
            field=models.EmailField(default=12, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_number',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='employee_portal.client'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='extra_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_blocklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='main_status',
            field=models.CharField(choices=[('SCREENING', 'Screening'), ('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('NOT_MATCHED', 'Not Matched'), ('HOLD', 'Hold'), ('OTHER', 'Other')], default='SCREENING', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='sub_status',
            field=models.CharField(choices=[('NONE', 'None'), ('DONE', 'Done'), ('SELECTED', 'Selected')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='employee_portal.vendor'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='vendor_company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='years_of_experience_calculated',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='years_of_experience_manual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='candidates/resumes/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='submitted_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CandidateRemarkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remark_history', to='employee_portal.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(max_length=50)),
                ('sub_status', models.CharField(blank=True, max_length=50, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='employee_portal.candidate')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RemarkHistory',
        ),
        migrations.DeleteModel(
            name='StatusHistory',
        ),
    ]
