# Generated by Django 5.2.10 on 2026-02-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0005_remove_statushistory_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
