# Generated by Django 5.2.10 on 2026-02-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0006_alter_candidate_candidate_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='technology',
            field=models.CharField(blank=True, max_length=10055, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='years_of_experience_manual',
            field=models.CharField(blank=True, null=True),
        ),
    ]
