# Generated by Django 5.2.10 on 2026-02-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0007_alter_candidate_technology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='years_of_experience_manual',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
