# Generated by Django 5.2.10 on 2026-02-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0009_client_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='main_status',
            field=models.CharField(choices=[('SCREENING', 'Screening'), ('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('OTHER', 'Other'), ('NOT_MATCHED', 'Not Matched'), ('HOLD', 'Hold'), ('REJECTED', 'Rejected'), ('SELECTED', 'Selected')], default='SCREENING', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='sub_status',
            field=models.CharField(choices=[('NONE', 'None'), ('DONE', 'Done'), ('SELECTED', 'Selected'), ('SCHEDULED', 'Scheduled'), ('SELECTED_WAIT_FOR_NEXT_ROUND', 'Selected Wait For Next Round')], default='NONE', max_length=100),
        ),
    ]
