# Generated by Django 5.2.10 on 2026-02-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0010_alter_candidate_main_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='sub_status',
            field=models.CharField(choices=[('NONE', 'None'), ('FINAL_SELECTED', 'Final Selected'), ('SCHEDULED', 'Scheduled'), ('SELECTED_WAIT_FOR_NEXT_ROUND', 'Selected Wait For Next Round'), ('WAIT_FOR_THE_UPDATE', 'Wait For The Update'), ('REJECTED', 'Rejected'), ('POSTPONED', 'Postponed')], default='NONE', max_length=100),
        ),
    ]
