# Generated by Django 5.2.10 on 2026-02-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0011_alter_candidate_sub_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='sub_status',
            field=models.CharField(choices=[('NONE', 'None'), ('DONE_WAIT_FOR_THE_UPDATE', 'Done,Wait For The Update'), ('FINAL_SELECTED', 'Final Selected'), ('SCHEDULED', 'Scheduled'), ('SELECTED_WAIT_FOR_NEXT_ROUND', 'Selected Wait For Next Round'), ('HOLD', 'Hold'), ('REJECTED', 'Rejected'), ('POSTPONED', 'Postponed')], default='NONE', max_length=100),
        ),
    ]
