# Generated by Django 5.2.10 on 2026-02-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0014_vendor_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='client_rate_type',
            field=models.CharField(blank=True, choices=[('LPM', 'LPM'), ('KPM', 'KPM'), ('PHR', 'PHR'), ('LPA', 'LPA')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='vendor_rate_type',
            field=models.CharField(blank=True, choices=[('LPM', 'LPM'), ('KPM', 'KPM'), ('PHR', 'PHR'), ('LPA', 'LPA')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='main_status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SCREENING', 'Screening'), ('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('OTHER', 'Other'), ('OFFERED', 'Offered'), ('ONBORD', 'onbord'), ('ON_HOLD', 'On Hold'), ('WITHDRAWN', 'Withdrawn'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='sub_status',
            field=models.CharField(choices=[('NONE', 'None'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('FEEDBACK_PENDING', 'Feedback Pending'), ('CLEARED', 'CLEARED'), ('REJECTED', 'Rejected'), ('POSTPONED', 'Postponed'), ('NO_SHOW', 'No Show'), ('ON_HOLD', 'On Hold'), ('INTERVIEW_PENDING', 'Interview Pending')], default='NONE', max_length=100),
        ),
    ]
