# Generated by Django 5.2.10 on 2026-02-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0015_candidate_client_rate_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_employee_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='msa_document',
            field=models.FileField(blank=True, null=True, upload_to='clients/msa/'),
        ),
        migrations.AddField(
            model_name='client',
            name='msa_status',
            field=models.CharField(blank=True, choices=[('NOT_SENT', 'Not Sent'), ('SENT', 'Sent'), ('SIGNED', 'Signed')], default='NOT_SENT', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='msa_uploaded_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='nda_document',
            field=models.FileField(blank=True, null=True, upload_to='clients/nda/'),
        ),
        migrations.AddField(
            model_name='client',
            name='nda_status',
            field=models.CharField(blank=True, choices=[('NOT_SENT', 'Not Sent'), ('SENT', 'Sent'), ('SIGNED', 'Signed')], default='NOT_SENT', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='nda_uploaded_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='official_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sending_email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='company_employee_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='msa_document',
            field=models.FileField(blank=True, null=True, upload_to='vendors/msa/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='msa_status',
            field=models.CharField(blank=True, choices=[('NOT_SENT', 'Not Sent'), ('SENT', 'Sent'), ('SIGNED', 'Signed')], default='NOT_SENT', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='msa_uploaded_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='nda_document',
            field=models.FileField(blank=True, null=True, upload_to='vendors/nda/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='nda_status',
            field=models.CharField(blank=True, choices=[('NOT_SENT', 'Not Sent'), ('SENT', 'Sent'), ('SIGNED', 'Signed')], default='NOT_SENT', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='nda_uploaded_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='provide_bench',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='provide_market',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='sending_email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_official_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
