# Generated by Django 5.2.10 on 2026-02-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0018_client_assigned_employees_client_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='vendor_company_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='vendor_number',
        ),
    ]
