# Generated by Django 5.2.10 on 2026-02-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0019_remove_candidate_vendor_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
