# Generated by Django 5.2.10 on 2026-03-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0021_candidate_google_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='billing_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='billing_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='default_billing_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='default_billing_rate_type',
            field=models.CharField(blank=True, choices=[('LPM', 'LPM'), ('KPM', 'KPM'), ('PHR', 'PHR'), ('LPA', 'LPA')], max_length=10, null=True),
        ),
    ]
