# Generated by Django 5.2.10 on 2026-05-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0024_candidate_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='client_rate_type',
            field=models.CharField(blank=True, choices=[('LPA', 'LPA (Lakh Per Annum)'), ('LPM', 'LPM (Lakh Per Month)'), ('KPM', 'KPM (Thousand Per Month)'), ('PHR', 'PHR (Per Hour - INR)'), ('USD', 'USD (US Dollar)'), ('USD_PH', 'USD/hr (US Dollar Per Hour)'), ('EUR', 'EUR (Euro)'), ('EUR_PH', 'EUR/hr (Euro Per Hour)'), ('GBP', 'GBP (Great Britain Pound)'), ('GBP_PH', 'GBP/hr (Pound Per Hour)'), ('AED', 'AED (UAE Dirham)'), ('SGD', 'SGD (Singapore Dollar)'), ('SAR', 'SAR (Saudi Riyal)'), ('CNY', 'CNY (Chinese Yuan)'), ('JPY', 'JPY (Japanese Yen)'), ('AUD', 'AUD (Australian Dollar)'), ('CAD', 'CAD (Canadian Dollar)'), ('CHF', 'CHF (Swiss Franc)'), ('HKD', 'HKD (Hong Kong Dollar)'), ('THB', 'THB (Thai Baht)'), ('MYR', 'MYR (Malaysian Ringgit)'), ('KRW', 'KRW (South Korean Won)'), ('NZD', 'NZD (New Zealand Dollar)'), ('NOK', 'NOK (Norwegian Krone)'), ('SEK', 'SEK (Swedish Krona)'), ('DKK', 'DKK (Danish Krone)'), ('ZAR', 'ZAR (South African Rand)'), ('RUB', 'RUB (Russian Ruble)'), ('KWD', 'KWD (Kuwaiti Dinar)'), ('QAR', 'QAR (Qatari Riyal)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='default_billing_rate_type',
            field=models.CharField(blank=True, choices=[('LPA', 'LPA (Lakh Per Annum)'), ('LPM', 'LPM (Lakh Per Month)'), ('KPM', 'KPM (Thousand Per Month)'), ('PHR', 'PHR (Per Hour - INR)'), ('USD', 'USD (US Dollar)'), ('USD_PH', 'USD/hr (US Dollar Per Hour)'), ('EUR', 'EUR (Euro)'), ('EUR_PH', 'EUR/hr (Euro Per Hour)'), ('GBP', 'GBP (Great Britain Pound)'), ('GBP_PH', 'GBP/hr (Pound Per Hour)'), ('AED', 'AED (UAE Dirham)'), ('SGD', 'SGD (Singapore Dollar)'), ('SAR', 'SAR (Saudi Riyal)'), ('CNY', 'CNY (Chinese Yuan)'), ('JPY', 'JPY (Japanese Yen)'), ('AUD', 'AUD (Australian Dollar)'), ('CAD', 'CAD (Canadian Dollar)'), ('CHF', 'CHF (Swiss Franc)'), ('HKD', 'HKD (Hong Kong Dollar)'), ('THB', 'THB (Thai Baht)'), ('MYR', 'MYR (Malaysian Ringgit)'), ('KRW', 'KRW (South Korean Won)'), ('NZD', 'NZD (New Zealand Dollar)'), ('NOK', 'NOK (Norwegian Krone)'), ('SEK', 'SEK (Swedish Krona)'), ('DKK', 'DKK (Danish Krone)'), ('ZAR', 'ZAR (South African Rand)'), ('RUB', 'RUB (Russian Ruble)'), ('KWD', 'KWD (Kuwaiti Dinar)'), ('QAR', 'QAR (Qatari Riyal)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='main_status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SCREENING', 'Screening'), ('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('OTHER', 'Other'), ('OFFERED', 'Offered'), ('ONBORD', 'onbord'), ('ON_HOLD', 'On Hold'), ('WITHDRAWN', 'Withdrawn'), ('REJECTED', 'Rejected'), ('OFFBOARDED', 'Offboarded')], default='SUBMITTED', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='vendor_rate_type',
            field=models.CharField(blank=True, choices=[('LPA', 'LPA (Lakh Per Annum)'), ('LPM', 'LPM (Lakh Per Month)'), ('KPM', 'KPM (Thousand Per Month)'), ('PHR', 'PHR (Per Hour - INR)'), ('USD', 'USD (US Dollar)'), ('USD_PH', 'USD/hr (US Dollar Per Hour)'), ('EUR', 'EUR (Euro)'), ('EUR_PH', 'EUR/hr (Euro Per Hour)'), ('GBP', 'GBP (Great Britain Pound)'), ('GBP_PH', 'GBP/hr (Pound Per Hour)'), ('AED', 'AED (UAE Dirham)'), ('SGD', 'SGD (Singapore Dollar)'), ('SAR', 'SAR (Saudi Riyal)'), ('CNY', 'CNY (Chinese Yuan)'), ('JPY', 'JPY (Japanese Yen)'), ('AUD', 'AUD (Australian Dollar)'), ('CAD', 'CAD (Canadian Dollar)'), ('CHF', 'CHF (Swiss Franc)'), ('HKD', 'HKD (Hong Kong Dollar)'), ('THB', 'THB (Thai Baht)'), ('MYR', 'MYR (Malaysian Ringgit)'), ('KRW', 'KRW (South Korean Won)'), ('NZD', 'NZD (New Zealand Dollar)'), ('NOK', 'NOK (Norwegian Krone)'), ('SEK', 'SEK (Swedish Krona)'), ('DKK', 'DKK (Danish Krone)'), ('ZAR', 'ZAR (South African Rand)'), ('RUB', 'RUB (Russian Ruble)'), ('KWD', 'KWD (Kuwaiti Dinar)'), ('QAR', 'QAR (Qatari Riyal)')], max_length=10, null=True),
        ),
    ]
