# Generated by Django 5.2.10 on 2026-05-15 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0025_alter_candidate_client_rate_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='main_status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SCREENING', 'Screening'), ('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('OTHER', 'Other'), ('OFFERED', 'Offered'), ('ONBORD', 'onbord'), ('ON_HOLD', 'On Hold'), ('WITHDRAWN', 'Withdrawn'), ('REJECTED', 'Rejected'), ('OFFBOARDED', 'Offboarded'), ('NONE', 'None')], default='SUBMITTED', max_length=100),
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('file', models.FileField(upload_to='candidates/timesheets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='employee_portal.candidate')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_timesheets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('file', models.FileField(upload_to='candidates/vendor_invoices/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_invoices', to='employee_portal.candidate')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_vendor_invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
