# Generated by Django 5.2.10 on 2026-05-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0026_alter_candidate_main_status_timesheet_vendorinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='leave_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='total_working_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='working_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='total_amount_with_gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='total_amount_without_gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
