# Generated by Django 5.2.10 on 2026-03-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_user_parent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CENTRAL_ADMIN', 'Central Admin'), ('SUB_ADMIN', 'Sub Admin'), ('EMPLOYEE', 'Employee'), ('ACCOUNTANT', 'Accountant')], default='EMPLOYEE', max_length=20),
        ),
    ]
