# Generated by Django 5.2.10 on 2026-03-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_user_attendance_streak_user_last_attendance_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_points',
        ),
    ]
