# Generated by Django 5.2.10 on 2026-02-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecalendareventhistory',
            name='new_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatecalendareventhistory',
            name='new_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidatecalendareventhistory',
            name='previous_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatecalendareventhistory',
            name='previous_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
