# Generated by Django 5.2.10 on 2026-02-26 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_service', '0002_candidatecalendareventhistory_new_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatecalendareventhistory',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
